import { isAuthticated } from "@/helpers/isAuthenticated";
import axios from "axios";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { toast } from "react-toastify";
import { setCookie } from "cookies-next";

const Home = () => {
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [loading, setLoading] = useState(false);

  const router = useRouter();

  const BASE_URL = process.env.BASE_URL;

  // Submit Form
  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);

    try {
      const response = await axios.post(`${BASE_URL}/login`, {
        username,
        password,
      });
      localStorage.setItem("token", JSON.stringify(response.data.token));
      setUsername("");
      setPassword("");
      setLoading(false);
      router.replace("/orders");
      toast.success("Login Successful");
    } catch (error) {
      setLoading(false);
      toast.error(error.response?.data?.message);
      console.log(error);
    }
  };

  useEffect(() => {
    isAuthticated() && router.replace("/orders");
  }, []);

  return (
    <>
      <Head>
        <title>Login | Unshelled </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center items-center h-screen p-5">
        <form onSubmit={handleSubmit} className="max-h-[500px] max-w-[500px] w-[500px] p-8 md:p-10 border">
          <h1 className="text-black font-bold text-3xl">Login</h1>

          <div className="flex flex-col mt-10 space-y-2">
            <label htmlFor="Username"> Username </label>
            <input
              type="text"
              placeholder="Seller ID"
              name="username"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              className="text-black input rounded-none input-bordered focus:outline-offset-0 focus:outline-1 disabled:bg-[#ececec] disabled:text-black"
            />
          </div>

          <div className="flex flex-col mt-10 space-y-2">
            <label htmlFor="Password"> Password </label>
            <input
              type="password"
              placeholder="Seller Zip Code Prefix"
              name="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              className="text-black input rounded-none input-bordered focus:outline-offset-0 focus:outline-1 disabled:bg-[#ececec] disabled:text-black"
            />
          </div>

          <button className={`${loading && "loading"} btn btn-block rounded-none mt-10`} type="submit">
            {loading ? "" : "Login"}
          </button>
        </form>
      </main>
    </>
  );
};

export default Home;
