import { API } from "@/helpers/axios";
import { isAuthticated } from "@/helpers/isAuthenticated";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import React, { useEffect, useState } from "react";
import { toast } from "react-toastify";

const Dashboard = () => {
  const [user, setUser] = useState(null);
  const [orders, setOrders] = useState(null);
  const [loading, setLoading] = useState(false);
  const [count, setCount] = useState(5);

  const router = useRouter();

  const fetchOrders = async () => {
    const BASE_URL = process.env.BASE_URL;
    setLoading(true);

    try {
      const response = await API.get(`${BASE_URL}/order_items`);
      setOrders(response?.data?.data);

      setLoading(false);
    } catch (error) {
      setLoading(false);
      toast.error(error.response?.data?.error);
      console.log(error);
    }
  };

  useEffect(() => {
    !isAuthticated() && router.replace("/");
  }, []);

  useEffect(() => {
    fetchOrders();
  }, []);

  const logout = () => {
    localStorage.clear("token");
    router.replace("/");
  };

  return (
    <>
      <Head>
        <title>Dashboard | Unshelled </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen items-center justify-center p-10">
        {orders && orders?.length > 1 ? (
          <div className="md:max-w-[90%] mx-auto">
            <div className="flex justify-between mb-4">
              <h1 className="font-bold text-2xl mb-4">
                All your orders{" "}
                <span className="text-sm font-light ml-3 italic"> {orders?.length} orders in total </span>
              </h1>
              <button className="btn rounded-none" onClick={logout}>
                Logout
              </button>
            </div>
            <div className="overflow-x-auto">
              <table className="table w-full border rounded-none">
                <thead>
                  <tr>
                    <th>S/N</th>
                    <th>Order ID</th>
                    <th>Order Item ID</th>
                    <th>Product ID</th>
                    <th>Shipping Date</th>
                    <th>Price</th>
                    <th>Frieght Value</th>
                  </tr>
                </thead>
                <tbody>
                  {orders?.slice(0, count).map((order, id) => (
                    // <Link key={id} href={`/orders/${order?.order_id}`}>
                    <tr key={id} className="hover:bg-black cursor-pointer">
                      <td>{id + 1}</td>
                      <td>{order?.order_id}</td>
                      <td>{order?.order_item_id}</td>
                      <td>{order?.product_id}</td>
                      <td>{order?.shipping_limit_date}</td>
                      <td>{order?.price}</td>
                      <td>{order?.freight_value}</td>
                    </tr>
                    // </Link>
                  ))}
                </tbody>
              </table>
            </div>

            <div className="btn-group flex justify-end mt-5 gap-3">
              <button className="btn btn-outline">Previous page</button>
              <button className="btn btn-outline" onClick={() => setCount(count + 5)}>
                Next
              </button>
            </div>
          </div>
        ) : (
          <p>Loading...</p>
        )}
      </main>
    </>
  );
};

export default Dashboard;
